#!/bin/bash 
##toch hosts
###main_config
USERID=""
KEY=""
URL="https://api.telegram.org/bot$KEY/sendMessage"
TIMEOUT="10"

DATE_EXEC="$(date "+%d%b%Y-%H:%M:%S")"

TIMEOUT="10"


function telegram_sendMessage
{
curl -s --max-time $TIMEOUT -d "chat_id=$USERID&disable_web_page_preview=1&parse_mode=html&text=$TEXT" $URL > /dev/null
}

function  text_style
{
TEXT="<pre>Link__HOSTS__$DATE_EXEC</pre><pre>-------------------------------</pre><em>"$OUT"</em>"
}

###########################################################
cat hosts |  while read output
do
    ping -c 2 -i 0.2 -s 10 "$output" > /dev/null
    #NS=$(nslookup "$output")
    if [ $? -eq 0 ]; then
	echo "hostUP-$output" >>  htmp
    else
	echo "hostDOWN-$output" >> htmp
    fi
done
 OUT=$(cat htmp)
        text_style
        telegram_sendMessage

rm htmp*
sleep 10
